#!/usr/bin/env node
// Build /decks.html plus the .txt decklists it hands out.
//
//   node scripts/build-decks.mjs
//
// Reads data/decks.json (written by scripts/sync-decks.mjs) through
// shared/decks.mjs, which also feeds /top-100-playable.html so the two pages
// cannot print different numbers for the same corpus.
//
// WHAT THE READER CAME FOR. Tim asked for easy to download lists of the best
// custom decks you could make, for the physical game and for TCG Live. The
// useful fact that makes that a real deliverable rather than a page of prose is
// that POKEMON TCG LIVE IMPORTS A DECKLIST BY PASTE. So the page hands over an
// actual working artifact: a .txt file in the exact format the client's deck
// importer takes, and a copy button for the phone case where downloading a text
// file and finding it again is the worst part of the whole job.
//
// THE FILES ARE VERBATIM AND THAT IS THE WHOLE POINT. Every .txt is the export
// string Limitless's own Copy to Clipboard button writes, byte for byte, with
// nothing added. NOTHING MAY EVER BE PREPENDED TO ONE. A friendly header line,
// a url, a "generated by" credit or even a stray blank line at the top is text
// the reader will paste into the importer along with the deck, and the importer
// reads the whole clipboard. A decklist that fails to import is worse than no
// decklist, so the file holds the deck and nothing else, and the attribution
// lives on the page around it where it costs the reader nothing.
//
// THE FORMAT WAS READ OFF A REAL ARTIFACT RATHER THAN REMEMBERED. Section
// headers are "Pokemon:", "Trainer:" and "Energy:" followed by the TOTAL number
// of cards in that section, not the number of distinct lines, which is a thing
// it is easy to get backwards. Card lines are "<qty> <name> <SET> <number>",
// space separated. Sections are separated by one blank line. There is no
// trailing "Total Cards" line in this shape. sync-decks.mjs asserts every list
// sums to exactly 60 before it is allowed into the corpus.
//
// WHAT THE RANKING MEASURES, in one sentence, because this is the claim the
// page lives or dies on: these are the MOST PLAYED decks, ordered by share of
// the recorded field, in ONLINE tournaments played in Pokemon TCG Live on
// Limitless's play platform. They are not paper Regionals, they are not Worlds,
// and "best deck" is a claim this site cannot source and therefore never makes.
// Win rate is printed but never sets the order, and is labelled as the separate
// measurement it is.
//
// LEGALITY IS BY CONSTRUCTION, NOT BY ADJUDICATION. Every list is drawn through
// Limitless's own Standard / 2026 rotation filter, so this builder never
// decides whether a card is legal. The rotation itself is an official Pokemon
// fact and is printed with both of its effective dates and the date we read it,
// because "current format" is a claim with an expiry and a page that says
// "current" without saying current as of when goes stale silently.
//
// NO PULL RATES, NO DROP RATES, NO ODDS, and no link to anything stating them.
// See CLAUDE.md. This is a deckbuilding page and there is no version of "how
// likely are you to open this card" that belongs on it.
//
// NO OUTBOUND LINKS. The sources are named in plain text at the foot instead.
// CLAUDE.md's rule is that every click stays on the site, with five documented
// exceptions, and this page did not need to become a sixth: Limitless is
// credited by name, which is what attribution requires, and a reader who wants
// it can find it. See the note in CLAUDE.md under the outbound rule.
//
// NO BACKTICKS IN COMMENTS IN THIS FILE. The page is one template literal and a
// backtick in a comment closes it.

import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SITE } from "../shared/site.mjs";
// NEITHER packplayer.js NOR packs.css. Nothing on this page plays a rip where
// it sits, so both attach to nothing: ~11.9KB gzipped and 2 requests for a
// script that finds no tile and a stylesheet whose classes never appear.
// CHECKED BY DRIVING THE PAGE, not by grepping it: packplayer's entry point is
// a delegated click on an <a> to a rip that WRAPS an <img> or a .pack facade,
// which no scan for [data-vcar] or img[data-packsrc] can see. The three
// conditions a page must meet, and why the obvious scan gives the wrong answer,
// are in shared/chrome.mjs beside the two exports. READ THAT BEFORE ADDING A
// VIDEO TILE OR A CAROUSEL HERE: a tile added without putting packplayer.js
// back navigates instead of playing in place, which reads as a design choice
// rather than as a bug.
import {
  BAR, MENU, SPRITE, SKIP, footer, FONTS,
  STYLES_NO_PACKS_CSS as STYLES,
  APP_JS_NO_PACKPLAYER as APP_JS,
} from "../shared/chrome.mjs";
import { esc, longDate, imgDims, avifPicture } from "../shared/format.mjs";
import { loadDecks, checkSetMap } from "../shared/decks.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const { d, resolve, byKey } = await loadDecks();
const map = checkSetMap(d, byKey);

const fmt = d.format;
const src = d.source;
const corpus = d.corpus;

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

// ---------------------------------------------------------------------------
// The .txt files.
// ---------------------------------------------------------------------------

const OUTDIR = join(ROOT, "public/decks");
// Cleared and rewritten, so an archetype that drops out of the metagame does
// not leave a stale file being linked from nowhere and found by search.
await rm(OUTDIR, { recursive: true, force: true });
await mkdir(OUTDIR, { recursive: true });

// POSITION IS RENUMBERED 1..N AND IS NOT LIMITLESS'S OWN RANK. Their table
// carries an "Other" bucket, which sits 11th by share and is not a deck: it
// cannot be built, downloaded or linked, so sync-decks.mjs drops it. Printing
// the untouched ranks after that left the page running 1 to 10, then 12 to 19,
// under a heading saying eighteen decks, so a reader could only conclude
// something had been quietly withheld. Renumbering changes no order, because
// removing one row from a list sorted by share cannot reorder the rest, and the
// page says the bucket was dropped and why.
const decks = d.decks.map((arch, i) => {
  const list = arch.lists[0];
  const slug = slugify(arch.name);
  return { ...arch, pos: i + 1, slug, list, file: `/decks/${slug}.txt` };
});

for (const deck of decks) {
  // Verbatim, plus the single trailing newline every text file ought to end
  // with. Nothing else. See the header.
  await writeFile(join(OUTDIR, `${deck.slug}.txt`), `${deck.list.text}\n`);
}

// ---------------------------------------------------------------------------
// Picking the cards to show for each deck.
// ---------------------------------------------------------------------------

/**
 * The faces of the deck.
 *
 * Sorted so the Pokemon the ARCHETYPE IS NAMED AFTER come first, then by how
 * many copies are played. Sorting by copies alone puts four Dreepy ahead of the
 * two Dragapult ex the deck is named for and built around, which reads as the
 * wrong picture even though the number is right.
 */
function faces(arch, list, n = 4) {
  const words = arch.name.toLowerCase().split(/\s+/).filter((w) => w.length > 2);
  return list.cards["Pokémon"]
    .map((c) => {
      const name = c.name.toLowerCase();
      const named = words.some((w) => name.includes(w));
      return { ...resolve(c), named, score: (named ? 1000 : 0) + c.qty };
    })
    .filter((c) => c.img)
    .sort((a, b) => b.score - a.score)
    .slice(0, n);
}

const cardImg = (c, cls = "dk-card") => {
  const alt = `${c.name}, ${c.setName || c.set} ${c.number}`;
  const img =
    `<img class="${cls}" src="${c.img}" alt="${esc(alt)}" loading="lazy" decoding="async"` +
    `${imgDims(c.img)} onerror="this.remove()">`;
  return avifPicture(img);
};

// ---------------------------------------------------------------------------
// The visible decklist.
// ---------------------------------------------------------------------------

const SECTIONS = ["Pokémon", "Trainer", "Energy"];

/**
 * The list as readable text.
 *
 * The page shows the whole thing rather than only offering the file, because a
 * reader on a phone may want to READ a deck to decide whether to build it, and
 * a page of download buttons is not an information page. The <pre> also holds
 * the exact text the copy button puts on the clipboard, so there is one copy of
 * the decklist in the markup rather than two that can drift.
 */
function listBlock(deck, i) {
  const cols = SECTIONS.map((sec) => {
    const cards = deck.list.cards[sec] || [];
    if (!cards.length) return "";
    const total = cards.reduce((n, c) => n + c.qty, 0);
    const rows = cards
      .map((c) => {
        const r = resolve(c);
        const label = `<span class="dk-q">${c.qty}</span> ${esc(c.name)}`;
        const code = `<span class="dk-set">${esc(c.set)} ${esc(c.number)}</span>`;
        // Link the row to the set guide when this site has one. This is the
        // cross-linking that stops the page being an orphan: a reader who wants
        // to know what a card costs or what else is in that set is one tap away
        // from a page we already wrote.
        return r.slug
          ? `<li><a href="/sets/${r.slug}.html">${label} ${code}</a></li>`
          : `<li><span class="dk-nolink">${label} ${code}</span></li>`;
      })
      .join("");
    return `<div class="dk-col"><h4>${esc(sec)} <span class="dk-n">${total}</span></h4><ul>${rows}</ul></div>`;
  }).join("");

  return `<div class="dk-cols">${cols}</div>
<details class="dk-raw">
  <summary>Show the raw import text</summary>
  <pre id="dk-text-${i}" class="dk-pre">${esc(deck.list.text)}</pre>
  <div class="dk-acts">
    <button type="button" class="dk-copy" data-target="dk-text-${i}">Copy the list</button>
    <a class="dk-dl" href="${deck.file}" download>Download the .txt</a>
  </div>
</details>`;
}

// ---------------------------------------------------------------------------
// Page.
// ---------------------------------------------------------------------------

const desc =
  `The ${decks.length} most played Pokemon decks in Standard, each with a free decklist ` +
  `you can download and paste straight into Pokemon TCG Live. Usage measured over ` +
  `${corpus.lists} tournament decklists.`;

const deckCards = decks
  .map((deck, i) => {
    const f = faces(deck, deck.list);
    const art = f.length
      ? `<div class="dk-faces">${f.map((c) => cardImg(c)).join("")}</div>`
      : "";
    const l = deck.list;
    return `<article class="dk" id="${deck.slug}">
  <header class="dk-head">
    <span class="dk-rank">${deck.pos}</span>
    <div class="dk-title">
      <h3>${esc(deck.name)}</h3>
      <p class="dk-share"><b>${deck.share}%</b> of the field
        <span class="dk-sep">/</span> ${deck.count.toLocaleString("en-US")} decks recorded
        ${deck.winPct != null ? `<span class="dk-sep">/</span> <span class="dk-win">${deck.winPct}% match win rate</span>` : ""}
      </p>
    </div>
  </header>
  ${art}
  <p class="dk-prov">The list below is <b>${esc(l.player)}</b>'s, ${esc(l.placing)} at
    ${esc(l.tournament)} on ${esc(longDate(l.date))}${l.record ? `, ${esc(l.record)}` : ""}.</p>
  ${listBlock(deck, i)}
</article>`;
  })
  .join("\n");

const ld = [
  {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: "Pokemon deck builds you can download",
    description: desc,
    datePublished: d.checked,
    dateModified: d.checked,
    author: { "@type": "Organization", name: "Garbage Rips 585" },
    publisher: { "@type": "Organization", name: "Garbage Rips 585" },
    mainEntityOfPage: `${SITE}/decks.html`,
  },
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: `${SITE}/` },
      { "@type": "ListItem", position: 2, name: "Deck builds", item: `${SITE}/decks.html` },
    ],
  },
];

const style = `
.dk-lede b{color:var(--ink)}
.dk-fmt{border:2px solid var(--keyline);border-radius:var(--r);background:var(--card);
  padding:var(--s4);margin:var(--s5) 0;box-shadow:var(--hard-lg)}
.dk-fmt h2{font-size:var(--t-m);margin:0 0 var(--s2)}
.dk-fmt dl{display:grid;grid-template-columns:1fr;gap:var(--s2) var(--s4);margin:0}
.dk-fmt dt{font-family:var(--mono);font-size:var(--t-micro);letter-spacing:.04em;
  text-transform:uppercase;color:var(--ink-2)}
.dk-fmt dd{margin:0 0 var(--s3);font-size:var(--t-sm);max-width:46em}
/* MEASURED IN REAL CHARACTERS, NOT IN ch. At 1440 the wrap is 1,392px and the
   prose here was unconstrained: .dk-prov ran 136 characters a line at 11px and
   the numbered steps ran 155 at 14px. The caps were set by measuring rendered
   line boxes and dividing real text length by real line count. "ch" would have
   been the wrong unit: it is the advance width of a "0", about 1.43 average
   characters in Outfit, so a 75ch rule buys a 107 character line.

   MEASURED AFTER, at 1440: 93 to 108 on the 11px notes, which is the same 46em
   the site already uses for a source note elsewhere, and the same trade
   /top-100-playable.html records. At 390 the same rules measure 67 to 73 and
   nothing below 1000px moves, because the wrap is already narrower than the
   cap there. */
.dk-p{max-width:38em}
.dk-mark{display:inline-block;font-family:var(--mono);font-weight:700;
  background:var(--chip-gold-bg);border:1px solid var(--gold-deep);color:var(--gold-deep);
  border-radius:var(--r-sm);padding:1px 7px;margin-right:4px}
.dk-asof{font-size:var(--t-micro);color:var(--ink-2);margin:var(--s3) 0 0;line-height:1.6;max-width:46em}

.dk-steps{counter-reset:dkstep;list-style:none;padding:0;margin:var(--s4) 0 0}
.dk-steps li{counter-increment:dkstep;position:relative;padding-left:2.2em;margin-bottom:var(--s3);max-width:46em;
  font-size:var(--t-sm);line-height:1.65}
.dk-steps li::before{content:counter(dkstep);position:absolute;left:0;top:0;
  width:1.6em;height:1.6em;display:grid;place-items:center;border-radius:50%;
  background:var(--chrome-bg);color:var(--chrome-ink);font-family:var(--mono);
  font-size:var(--t-micro);font-weight:700}

.dk-jump{margin:var(--s4) 0 var(--s5)}
.dk-jump ul{list-style:none;padding:0;margin:0;display:flex;flex-wrap:wrap;gap:var(--s2)}
.dk-jump a{display:flex;gap:6px;align-items:baseline;text-decoration:none;color:var(--ink);
  border:2px solid var(--keyline);border-radius:var(--r-pill);padding:5px var(--s3);
  font-size:var(--t-sm);background:var(--card)}
.dk-jump a:hover,.dk-jump a:focus{background:var(--mustard)}
.dk-jump b{color:var(--gold-deep);font-family:var(--mono)}
.dk-jump span{font-size:var(--t-micro);color:var(--ink-2)}
/* The anchor target sits under the sticky bar without this. Same offset the
   bar's own height token declares, so a taller bar cannot desync it. */
.dk{scroll-margin-top:calc(var(--bar-h) + var(--s3))}
.dk{border:2px solid var(--keyline);border-radius:var(--r);background:var(--card);
  padding:var(--s4);margin:0 0 var(--s5);box-shadow:var(--hard-lg)}
.dk-head{display:flex;gap:var(--s3);align-items:flex-start}
.dk-rank{font-family:var(--display);font-size:1.5rem;line-height:1;color:var(--gold-deep);
  min-width:1.6em}
.dk-title h3{margin:0;font-size:var(--t-m);line-height:1.2}
.dk-share{margin:var(--s1) 0 0;font-size:var(--t-sm);color:var(--ink-2)}
.dk-share b{color:var(--ink)}
.dk-sep{color:var(--hair)}
.dk-win{white-space:nowrap}
/* FOUR EQUAL COLUMNS, NOT A WRAPPING FLEX ROW. At a fixed 88px the four scans
   measured 376px against 354px of usable width inside the card at 390, so the
   fourth wrapped onto its own line and the deck's key cards read as "three
   cards, and one afterthought". A grid divides whatever width there is by four,
   so the row is always four across and the art scales instead of wrapping.
   max-width stops them ballooning on a wide desktop where the card is roomy. */
.dk-faces{display:grid;grid-template-columns:repeat(4,1fr);gap:var(--s2);
  margin:var(--s3) 0 0;max-width:480px}
/* The scans are 245x337 intrinsic; width/height stay on the tag for the aspect
   ratio and the box is what decides the transfer, not the file. */
.dk-card{width:100%;height:auto;border-radius:var(--r-sm);display:block}
.dk-prov{font-size:var(--t-micro);color:var(--ink-2);margin:var(--s3) 0 0;line-height:1.6;max-width:46em}

.dk-cols{display:grid;grid-template-columns:1fr;gap:var(--s4);margin:var(--s4) 0 0}
.dk-col h4{margin:0 0 var(--s2);font-size:var(--t-label);font-family:var(--mono);
  text-transform:uppercase;letter-spacing:.05em;color:var(--ink-2);
  border-bottom:1px solid var(--hair);padding-bottom:var(--s1)}
.dk-n{float:right;color:var(--ink)}
.dk-col ul{list-style:none;padding:0;margin:0}
.dk-col li{font-size:var(--t-sm);line-height:1.55;padding:1px 0}
.dk-col a{text-decoration:none;color:var(--ink);display:block}
.dk-col a:hover,.dk-col a:focus{text-decoration:underline}
.dk-nolink{display:block;color:var(--ink)}
.dk-q{font-family:var(--mono);font-weight:700;color:var(--gold-deep);margin-right:2px}
.dk-set{font-family:var(--mono);font-size:var(--t-micro);color:var(--ink-2);white-space:nowrap}

.dk-raw{margin:var(--s4) 0 0;border-top:1px solid var(--hair);padding-top:var(--s3)}
.dk-raw summary{font-size:var(--t-sm);cursor:pointer;font-weight:600}
.dk-pre{font-family:var(--mono);font-size:var(--t-micro);line-height:1.55;
  background:var(--paper-3);border-radius:var(--r-sm);padding:var(--s3);
  overflow-x:auto;margin:var(--s3) 0 0;white-space:pre}
.dk-acts{display:flex;gap:var(--s2);flex-wrap:wrap;margin:var(--s3) 0 0}
.dk-copy,.dk-dl{font:inherit;font-size:var(--t-sm);font-weight:600;cursor:pointer;
  border:2px solid var(--keyline);border-radius:var(--r-sm);padding:var(--s2) var(--s3);
  text-decoration:none;display:inline-block}
.dk-copy{background:var(--mustard);color:var(--on-accent)}
.dk-dl{background:var(--card);color:var(--ink)}

.dk-more{display:grid;grid-template-columns:1fr;gap:var(--s3);margin:var(--s4) 0 0;
  list-style:none;padding:0}
.dk-more a{display:block;border:2px solid var(--keyline);border-radius:var(--r);
  background:var(--card);padding:var(--s3);text-decoration:none;color:var(--ink);
  box-shadow:var(--hard-lg)}
.dk-more b{display:block;font-size:var(--t-sm)}
.dk-more span{font-size:var(--t-micro);color:var(--ink-2);line-height:1.5;display:block;
  margin-top:2px}
.dk-src{font-size:var(--t-micro);color:var(--ink-2);margin-top:var(--s6);line-height:1.7;
  max-width:46em}

@media(min-width:700px){
  .dk-fmt dl{grid-template-columns:auto 1fr}
  .dk-fmt dt{text-align:right;padding-top:2px}
  .dk-cols{grid-template-columns:1.2fr 1.4fr .8fr}
  .dk-more{grid-template-columns:1fr 1fr}
  }
@media(min-width:1000px){
  .dk-more{grid-template-columns:repeat(4,1fr)}
  }
`;

const page = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pokemon Deck Builds You Can Download and Paste Into TCG Live | Garbage Rips 585</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${SITE}/decks.html">
<meta property="og:title" content="Deck builds you can download">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:type" content="article">
<meta property="og:url" content="${SITE}/decks.html">
<meta property="og:site_name" content="Garbage Rips 585">
<meta property="og:image" content="${SITE}/assets/og-decks.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="${SITE}/assets/og-decks.jpg">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" href="/favicon-32.png" type="image/png" sizes="32x32">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="theme-color" content="#111111">
${FONTS}
${STYLES}
<style>${style}</style>
${ld.map((o) => `<script type="application/ld+json">${JSON.stringify(o)}</script>`).join("\n")}
</head>
<body>
${SPRITE}
${SKIP}
${BAR}
${MENU}
<main id="main">
  <section class="tight">
    <div class="wrap">
      <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <span>Deck builds</span></nav>
      <h1>Deck builds you can <span class="hl">download</span> and paste into TCG Live</h1>
      <p class="lede dk-lede">Every deck below comes with the real decklist, in the exact text format
        <b>Pokemon TCG Live's deck importer takes</b>. Copy it or download the file, hit Import Deck in the
        client, paste, done. The same 60 cards is a legal deck in the paper game too, because they are
        the same game.</p>

      <div class="dk-fmt">
        <h2>The format these decks are legal in</h2>
        <dl>
          <dt>Format</dt>
          <dd><b>${esc(fmt.name)}</b></dd>
          <dt>Legal marks</dt>
          <dd>${fmt.legalMarks.map((m) => `<span class="dk-mark">${esc(m)}</span>`).join("")}
            and any newer ones. Look at the bottom corner of the card.</dd>
          <dt>Rotated out</dt>
          <dd>${fmt.rotatedOut.map((m) => `<span class="dk-mark">${esc(m)}</span>`).join("")}
            no longer legal.</dd>
          <dt>In force since</dt>
          <dd>${esc(longDate(fmt.liveEffective))} in Pokemon TCG Live,
            ${esc(longDate(fmt.paperEffective))} at in-person events. The two dates are genuinely
            different and the digital one came first.</dd>
        </dl>
        <p class="dk-asof">Source: ${esc(fmt.source)}, read ${esc(longDate(fmt.read))}.
          Rotation is announced by Pokemon and it changes, so treat this as correct as of that date
          rather than forever. Every list on this page was drawn through Limitless's own Standard
          filter for this rotation, so the decks are format legal because of where they came from,
          not because we checked them card by card.</p>
      </div>

      <h2>How to get one of these into the game</h2>
      <ol class="dk-steps">
        <li>Pick a deck below and open <b>Show the raw import text</b>.</li>
        <li>Hit <b>Copy the list</b>, or download the .txt if you would rather keep it.</li>
        <li>In Pokemon TCG Live, open the deck manager, choose <b>Create a Deck</b>, then <b>Import Deck</b>.</li>
        <li>Paste into the import box and confirm. Cards you do not own yet show as missing, and you can
          craft them or build round them. New to the client? <a href="/tcg-live.html">Start here</a>.</li>
      </ol>
      <p class="dk-asof">The .txt files hold the decklist and absolutely nothing else, no header and no
        credit line, because the importer reads everything you paste and a stray line is how an import
        fails.</p>

      <h2>What "most played" means here, exactly</h2>
      <p class="dk-p">These are the <b>most played</b> decks, ordered by <b>share of the recorded field</b>. That is a
        different claim from "the best decks", which is not something this site can source, so it is not a
        claim made anywhere on this page. Match win rate is printed next to each deck because leaving it
        out would be its own distortion, but it never sets the order.</p>
      <p class="dk-asof">Measured by <b>${esc(src.name)}</b> across ${src.sample.tournaments.toLocaleString("en-US")}
        tournaments, ${src.sample.players.toLocaleString("en-US")} players and
        ${src.sample.matches.toLocaleString("en-US")} matches, filtered to ${esc(src.filter)}, read
        ${esc(longDate(d.checked))}.
        <b>These are online tournaments played in Pokemon TCG Live</b> on Limitless's own play platform,
        the kind community organisers run for booster-code prizes. They are not Regionals, not
        Internationals and not the World Championships, and nothing here is a paper result. That is the
        honest description of the sample, and it happens to be the right sample for this page, because the
        question is what to build and play in the client.</p>

      <h2>The ${decks.length} most played decks</h2>
      <p class="dk-asof">Each one shows the highest placing list of that deck in the sample, dated and
        credited to the player who registered it. Lists collected run
        ${esc(longDate(corpus.earliest))} to ${esc(longDate(corpus.latest))}. Numbered in order of share.
        Limitless's own table also carries an "Other" bucket, which would sit eleventh: it is everything
        too rare to name rather than a deck, so it is left out here and the rest are numbered straight
        through.</p>

      ${/* A JUMP LIST, because this page is 26,897px tall at 390 and eighteen full
           60-card decklists is a lot of thumb between the top and the deck you
           came for. Measured before it was added: reaching the last deck meant
           scrolling past roughly 1,000 card rows. It is a nav element rather
           than decoration, so it is a <nav> with a label. */ ""}
      <nav class="dk-jump" aria-label="Jump to a deck">
        <ul>
          ${decks
            .map(
              (deck) =>
                `<li><a href="#${deck.slug}"><b>${deck.pos}</b> ${esc(deck.name)}
                  <span>${deck.share}%</span></a></li>`
            )
            .join("")}
        </ul>
      </nav>

      ${deckCards}

      <h2>Where to go next</h2>
      <ul class="dk-more">
        <li><a href="/top-100-playable.html"><b>The 100 most played cards</b>
          <span>What actually goes in these decks, counted across all ${corpus.lists} lists</span></a></li>
        <li><a href="/tcg-live.html"><b>Pokemon TCG Live</b>
          <span>The free official client, and what the code card in every pack gives you</span></a></li>
        <li><a href="/how-to-play.html"><b>How to play</b>
          <span>Setup, a turn, and the three ways to win, if the deck is your first</span></a></li>
        <li><a href="/tcg-pocket.html"><b>Pokemon TCG Pocket</b>
          <span>The phone one, which is a different game and does not take these lists</span></a></li>
      </ul>

      <p class="dk-src">Deck usage, match records and every decklist come from <b>${esc(src.name)}</b>,
        read ${esc(longDate(d.checked))}: ${esc(src.what)}, filtered to ${esc(src.filter)}. Each list is
        reproduced exactly as its player registered it and is credited above. Regulation marks and both
        rotation dates come from ${esc(fmt.source)}, read ${esc(longDate(fmt.read))}. Card scans and card
        data from TCGdex. Card names and pictures were checked against this site's own card records:
        ${map.matched} of ${map.printings} distinct printings in these decks matched exactly, and the
        ${map.printings - map.matched} that did not are cards from sets this site has no guide for, so they
        are listed without a picture rather than with the wrong one. This page states no pull rates and no
        pack odds, because we do not have them.</p>
    </div>
  </section>
</main>
${footer("Deck data and decklists from Limitless TCG. Card scans from TCGdex.")}
<script>
// Copy the exact text out of the <pre> the reader is looking at. Reading it
// from the DOM rather than from a second copy in a data- attribute means there
// is one decklist in the markup and the button cannot drift from the file.
document.querySelectorAll('.dk-copy').forEach(function (b) {
  b.addEventListener('click', function () {
    var el = document.getElementById(b.dataset.target);
    if (!el) return;
    navigator.clipboard.writeText(el.textContent).then(function () {
      var was = b.textContent;
      b.textContent = 'Copied, now paste it into Live';
      setTimeout(function () { b.textContent = was; }, 2400);
    }, function () {
      b.textContent = 'Press and hold the list to copy';
    });
  });
});
</script>
${APP_JS}
</body>
</html>
`;

await writeFile(join(ROOT, "public/decks.html"), page);

const files = (await readdir(OUTDIR)).filter((f) => f.endsWith(".txt"));
console.log(`Wrote public/decks.html`);
console.log(
  `  ${decks.length} decks, ${files.length} decklist .txt files in public/decks/`
);
console.log(
  `  corpus ${corpus.lists} lists, ${corpus.earliest} to ${corpus.latest}, ` +
    `set map ${map.matched}/${map.printings} printings verified`
);
