#!/usr/bin/env python3
"""Turn pack artwork masters into web-sized files plus the CSS that uses them.

    python3 scripts/build-packs.py

Drop masters in assets-source/packs/ named by set id (pitch-black.png,
chaos-rising.png, default.png ...). This writes optimised WebP to
public/assets/packs/ and generates public/assets/packs.css, which is what
actually swaps a set's gradient for its artwork. A set with no master keeps
its colour design, so this is safe to run with one file or twenty.

Needs Pillow: python3 -m pip install --user Pillow
"""
import os
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets-source" / "packs"
OUT = ROOT / "public" / "assets" / "packs"
CSS = ROOT / "public" / "assets" / "packs.css"

# 810x1440 covers both places the pack renders: the rip page player needs
# 760px across at 2x, tiles need 534. One file, no srcset gymnastics.
TARGET = (810, 1440)
# A tile is never wider than about 200 CSS px, so 400 covers it at 2x. The full
# size exists for one place only: the rip page player, which is ~380 CSS px and
# needs 760. Serving 810x1440 into a 197px tile was a 4x linear oversample and
# put 1.6 MB of pack art on the home page.
TILE = (400, 711)
QUALITY = 78
BACKDROP = "#161D26"  # shows through the transparent margin around the pack

SRC.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)

masters = sorted(
    p for p in SRC.iterdir()
    if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp") and not p.name.startswith(".")
)

if not masters:
    print(f"No masters found in {SRC.relative_to(ROOT)}/")
    print("Drop 1080x1920 artwork named by set id, e.g. pitch-black.png")
    raise SystemExit(0)

rules = [
    "/* Generated by scripts/build-packs.py. Do not edit by hand. */",
    "/* A set listed here shows its artwork; every other set keeps the",
    "   colour design in site.css. */",
    "",
]
done = []
for m in masters:
    set_id = m.stem
    im = Image.open(m)
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    full = im.copy()
    full.thumbnail(TARGET, Image.LANCZOS)
    dest = OUT / f"{set_id}-garbage-rips-585-booster-pack.webp"
    full.save(dest, "WEBP", quality=QUALITY, method=6)

    tile = im.copy()
    tile.thumbnail(TILE, Image.LANCZOS)
    tile_dest = OUT / f"{set_id}-garbage-rips-585-booster-pack-tile.webp"
    tile.save(tile_dest, "WEBP", quality=QUALITY, method=6)

    kb = dest.stat().st_size / 1024
    tkb = tile_dest.stat().st_size / 1024
    done.append((set_id, full.size, kb, m.stat().st_size / 1024, tile.size, tkb))

    sel = f".pack--{set_id}"
    rules += [
        f"{sel} .pack-art{{",
        f"  background-color:{BACKDROP};",
        f"  background-image:url('packs/{set_id}-garbage-rips-585-booster-pack.webp');",
        "  background-size:cover;",
        "  background-position:center;",
        "}",
        # The artwork carries its own wordmark and mascot, so the generated
        # ones would sit on top of it.
        f"{sel} .pack-art::before,{sel} .pack-art::after{{content:none}}",
        f"{sel} .pack-brand,{sel} .pack-mascot{{display:none}}",
        # A tile is never wider than about 200 CSS px. Pointing it at the 810px
        # file was a 4x oversample, and the library draws 48 of them at once.
        f"{sel}.pack--tile .pack-art{{",
        f"  background-image:url('packs/{set_id}-garbage-rips-585-booster-pack-tile.webp');",
        "}",
        "",
    ]

# The Hall of Fame recolours every pack gold, which artwork would override.
rules += [
    "/* Hall of Fame stays gold even for sets that have artwork. The gold is",
    "   painted with gradients, so simply clearing background-image blanked",
    "   these to a flat dark rectangle. Restore the gradients explicitly. */",
    ".hall .pack .pack-art{",
    "  background-color:transparent;",
    "  background-image:",
    "    radial-gradient(120% 70% at 50% 12%,rgba(255,255,255,.22),transparent 60%),",
    "    linear-gradient(160deg,var(--pk-a) 0%,var(--pk-b) 38%,var(--pk-c) 72%,var(--pk-d) 100%);",
    "}",
    ".hall .pack .pack-art::before{content:\"\"}",
    ".hall .pack .pack-brand{display:block}",
    "",
]

CSS.write_text("\n".join(rules))

print(f"Wrote {len(done)} pack image(s) to {OUT.relative_to(ROOT)}/")
for set_id, size, kb, src_kb, tsize, tkb in done:
    print(f"  {set_id:<24} {size[0]}x{size[1]}  {kb:6.1f} KB   (from {src_kb:.0f} KB)")
print(f"\nWrote {CSS.relative_to(ROOT)}")

# ---------------------------------------------------------------- packshots
# Photos of the REAL retail booster packs, for the set pages. These have to be
# pictures you took yourself of packs you own: official product photography is
# not ours to copy. Any set without one just hides that panel.
SHOT_SRC = ROOT / "assets-source" / "packshots"
SHOT_OUT = ROOT / "public" / "assets" / "packshots"
SHOT_SRC.mkdir(parents=True, exist_ok=True)
SHOT_OUT.mkdir(parents=True, exist_ok=True)

shots = sorted(
    p for p in SHOT_SRC.iterdir()
    if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp") and not p.name.startswith(".")
)
if shots:
    print()
    for m in shots:
        im = Image.open(m)
        if im.mode not in ("RGB", "RGBA"):
            im = im.convert("RGBA")
        im.thumbnail((720, 1080), Image.LANCZOS)
        dest = SHOT_OUT / f"{m.stem}-booster-pack.webp"
        im.save(dest, "WEBP", quality=80, method=6)
        print(f"  packshot {m.stem:<22} {im.size[0]}x{im.size[1]}  {dest.stat().st_size/1024:6.1f} KB")
    print(f"\nWrote {len(shots)} packshot(s) to {SHOT_OUT.relative_to(ROOT)}/")
else:
    print(f"\nNo packshots in {SHOT_SRC.relative_to(ROOT)}/ yet.")
    print("Drop photos of real booster packs named by set id (pitch-black.jpg).")
