#!/usr/bin/env python3
"""Lay out the Garbage Rips 585 giveaway sticker for a print shop.

    python3 scripts/build-sticker.py

Writes assets-source/stickers/, which is NOT deployed. This is a print asset,
not a site asset, and it lives beside the pack art masters for the same reason
they do.

WHY THIS IS A SCRIPT AND NOT A ONE-OFF EXPORT. The owner will reprint these, and a
sticker regenerated by hand a year from now is a sticker whose wordmark has
drifted from the site's. Every colour below is READ OFF assets-source/ui.css by
name, the way scripts/build-og.py already does for the share cards, so the next
palette is a re-read rather than a taste decision.

THE ART IS 1300x725 AND THAT IS THE HONEST CEILING. It is the largest copy in
this repo. At 300dpi it prints 4.33 inches wide, which is a good giveaway size
and is as big as it can go without upscaling. A bigger sticker needs the
original from Unableplacebo, who drew it; do not enlarge this one to fake it.

THE TYPE SITS ON A PLATE RATHER THAN ON THE SKY, and that is measured, not a
preference. The top right of the art is BRIGHT: mean luminance 220 with a
standard deviation of 16 over the top strip, so it is calm as well as pale.
Off-white type would vanish there, and the brand's own wordmark is off-white
with a pink RIPS. Inverting to dark type would keep it legible and lose the
wordmark; a dark plate keeps both, and it lands on sky and rooftops rather than
on Trubbish, who sits centre-left. CLAUDE.md's rule that copy never goes over
this art is about the site HEADER, where the panel would have to span the full
width and would wash him out. Here it is a corner.
"""
import re
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "public/assets/banner-trubbish.jpg"
OUT = ROOT / "assets-source/stickers"
FONTS = ROOT / "assets-source/print-fonts"

DPI = 300
BLEED_IN = 0.125                      # what every print shop asks for
BLEED = round(BLEED_IN * DPI)         # 38px

# ---------------------------------------------------------------- the palette
# Read by NAME out of the stylesheet, never typed in. build-og.py takes the same
# approach and CLAUDE.md's palette section is emphatic about why: the token names
# on this site do not mean their colours (every "mustard" is a teal) and a hex
# copied by hand is a hex that stops tracking the site.
def tokens():
    css = (ROOT / "assets-source/ui.css").read_text(encoding="utf-8")
    want = ["ink", "ketchup", "mustard", "page", "chrome-bg", "on-accent", "keyline"]
    out = {}
    for name in want:
        m = re.search(rf"--{name}:\s*(#[0-9A-Fa-f]{{6}})", css)
        if not m:
            raise SystemExit(f"ui.css has no --{name}; read the stylesheet before editing this list")
        out[name] = m.group(1)
    return out


def font(name, size):
    return ImageFont.truetype(str(FONTS / name), size)


def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def build():
    C = {k: rgb(v) for k, v in tokens().items()}
    art = Image.open(ART).convert("RGB")
    AW, AH = art.size

    BAND = 162                        # the URL band under the art
    SAFE = 45                         # 0.15in: nothing important closer to the trim
    TW, TH = AW, AH + BAND            # trim size
    W, H = TW + BLEED * 2, TH + BLEED * 2

    # THE BLEED IS THE ART ITSELF, NOT A COLOURED MARGIN. A print shop cuts
    # through the bleed, so anything that is not a continuation of the picture
    # shows up as a sliver of the wrong colour on a mis-cut sticker. The art is
    # scaled up very slightly and centred so there is real picture out there.
    over = 1 + (BLEED * 2) / AW
    bg = art.resize((round(AW * over), round(AH * over)), Image.LANCZOS)
    card = Image.new("RGB", (W, H), C["page"])
    card.paste(bg, ((W - bg.width) // 2, BLEED + (AH - bg.height) // 2))
    # the band, drawn full width so it also fills the bottom bleed
    d = ImageDraw.Draw(card)
    d.rectangle([0, BLEED + AH, W, H], fill=C["page"])

    # ------------------------------------------------------- the wordmark plate
    ox, oy = BLEED, BLEED             # trim origin inside the bleed
    pad = 24
    # 58 rather than 66. The wordmark sets the plate's width, and every pixel of
    # plate is a pixel of the Rochester skyline covered -- which is the one part
    # of this drawing that says WHERE, on a sticker whose tagline says Rochester.
    f_mark = font("TitanOne.ttf", 58)
    # 29px, NOT 20. EVERY SIZE HERE IS CHECKED AS POINTS, because a sticker is
    # read at arm's length on a table and not on a screen: 72pt is one inch, so
    # at 300dpi a size in pixels divided by 300 and times 72 is what the printer
    # actually sets. The first draft had this tagline at 20px, which is 4.8pt --
    # smaller than the legal small print on a receipt, on the line the owner
    # specifically asked for. 29px is 7pt, which is the floor for something a
    # stranger is meant to read. The wordmark is 13.9pt and the url 12pt.
    f_tag = font("SpaceMono-b.ttf", 29)

    mark = [("GARBAGE ", C["ink"]), ("RIPS", C["ketchup"]), (" 585", C["ink"])]
    tag = "POKEMON PACK RIPS FROM ROCHESTER, NY"
    mw = sum(d.textlength(t, font=f_mark) for t, _ in mark)
    tw = d.textlength(tag, font=f_tag)
    inner = max(mw, tw)
    pw, ph = inner + pad * 2, 58 + 14 + 29 + pad * 2

    # SAFE, not 30. A sticker is guillotined or die-cut with real tolerance, and
    # anything inside 0.125in of the trim can lose a corner. Type gets 0.15in.
    px = ox + AW - pw - SAFE
    py = oy + SAFE
    plate = Image.new("RGBA", (round(pw), round(ph)), (*C["chrome-bg"], 236))
    mask = Image.new("L", plate.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, plate.width - 1, plate.height - 1], 22, fill=255)
    card.paste(plate.convert("RGB"), (round(px), round(py)), mask)
    d.rounded_rectangle([px, py, px + pw, py + ph], 22, outline=C["keyline"], width=2)

    x = px + pad
    for t, col in mark:
        d.text((x, py + pad - 6), t, font=f_mark, fill=col)
        x += d.textlength(t, font=f_mark)
    d.text((px + pad, py + pad + 58 + 10), tag, font=f_tag, fill=C["ink"])

    # ------------------------------------------------------------- the URL band
    # TEAL, because the accent rule on this site is that teal is every ROUTE and
    # pink is every mark that goes nowhere. A url is the most route-like thing
    # on the sticker, and it is the whole reason the sticker exists.
    f_url = font("SpaceMono-b.ttf", 86)
    url = "GARBAGERIPS.COM"
    by = BLEED + AH
    l, t, r, b = d.textbbox((0, 0), url, font=f_url)
    d.text(((W - (r - l)) / 2 - l, by + (BAND - (b - t)) / 2 - t),
           url, font=f_url, fill=C["mustard"])

    # THE FAN CONTENT LINE WAS HERE AND THE OWNER TOOK IT OFF, 2 September 2026:
    # "remove the disclaimer at the bottom". It was raised as worth keeping, he
    # decided, and it is his brand and his sticker. Recorded rather than argued
    # again, and note the site FOOTER still carries it on all 1,504 pages, which
    # is where CLAUDE.md's requirement actually sits -- nothing on the site
    # changed by taking it off a print asset. If a future sticker wants it back,
    # it was 23px / 5.5pt in --keyline under the url, at 4.19:1.

    OUT.mkdir(parents=True, exist_ok=True)
    card.save(OUT / "garbage-rips-sticker-print.png", dpi=(DPI, DPI))
    # THE PREVIEW IS ROUNDED AND THE PRINT FILE IS NOT, deliberately. A die-cut
    # rounded rectangle is what a shop actually cuts, so this is what the sticker
    # will look like in the hand; the file the shop receives has to be square and
    # full bleed so their cutter has material to take.
    trim = card.crop((BLEED, BLEED, BLEED + TW, BLEED + TH)).convert("RGBA")
    r = round(0.18 * DPI)             # ~0.18in corner, a common die
    m = Image.new("L", trim.size, 0)
    ImageDraw.Draw(m).rounded_rectangle([0, 0, TW - 1, TH - 1], r, fill=255)
    trim.putalpha(m)
    trim.save(OUT / "garbage-rips-sticker-preview.png", dpi=(DPI, DPI))
    print(f"  trim  {TW}x{TH}px = {TW/DPI:.2f} x {TH/DPI:.2f} in at {DPI}dpi")
    print(f"  bleed {W}x{H}px = {W/DPI:.2f} x {H/DPI:.2f} in ({BLEED_IN}in all round)")
    print(f"  wrote {OUT}/garbage-rips-sticker-print.png and -preview.png")


if __name__ == "__main__":
    build()
