#!/usr/bin/env node
// Strip the comments out of the site's three scripts for delivery.
//
//   node scripts/build-js.mjs
//
// Reads assets-source/js/*.js and writes public/assets/*.js. Same shape, and
// the same reasoning, as build-css.mjs: the SOURCE is the commented file, the
// thing the browser downloads is the same code with the prose taken out.
//
// WHY IT IS WORTH DOING. These three files are 54-60% comment by byte, and
// those comments are the project's memory -- why loading="lazy" stays on slide
// zero, why the ten-sale floor exists, what broke the last time somebody
// touched the carousel. They should never be deleted and they should never be
// downloaded. Measured, gzipped, which is what actually crosses the wire:
//
//     app.js         32.5 KB -> 10.4 KB
//     packplayer.js  11.9 KB ->  3.9 KB
//     games.js       10.4 KB ->  2.8 KB
//                              37.6 KB saved
//
// WHOLE LINES ONLY, AND THAT IS THE SAFETY PROPERTY. A real minifier has to
// tokenise, and the hard case is telling a regex literal from a division: these
// files carry 26 of the former and 56 of the latter, plus 82 backticks and two
// http:// inside strings, so a scanner that gets it wrong corrupts the site
// silently. This never edits a line that has code on it. It deletes lines that
// are nothing but a comment and leaves every other byte alone.
//
// A full tokeniser was written and measured first: 37.7 KB against this one's
// 37.6 KB. A tenth of a kilobyte is not worth the class of bug it buys.
//
// THE ONE WAY THIS CAN STILL BREAK is a comment-shaped line INSIDE a template
// literal -- a CSS block in a `...` string, say, whose lines start with /* or
// *. Deleting one of those would eat a live string. There are none today, in
// any of the three files, and assertNoTemplateComments below fails the build if
// one ever appears rather than quietly swallowing it.
import { readFile, writeFile, readdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "assets-source", "js");
const OUT = join(ROOT, "public", "assets");

/** Which lines begin inside a template literal, so they must not be touched. */
function templateLines(src) {
  const inside = new Set();
  let tpl = false, esc = false, line = 1;
  for (let i = 0; i < src.length; i += 1) {
    const ch = src[i];
    if (ch === "\n") { line += 1; if (tpl) inside.add(line); continue; }
    if (esc) { esc = false; continue; }
    if (ch === "\\") { esc = true; continue; }
    if (ch === "`") tpl = !tpl;
  }
  return inside;
}

function assertNoTemplateComments(name, src) {
  const inside = templateLines(src);
  const bad = [];
  src.split("\n").forEach((ln, i) => {
    const t = ln.trim();
    if (!inside.has(i + 1)) return;
    if (t.startsWith("//") || t.startsWith("/*") || t.startsWith("*")) bad.push([i + 1, t.slice(0, 60)]);
  });
  if (bad.length) {
    throw new Error(
      `${name}: ${bad.length} comment-shaped line(s) sit INSIDE a template literal, so ` +
        `stripping them would delete live string content:\n  ` +
        bad.map(([n, t]) => `line ${n}: ${t}`).join("\n  ") +
        `\nMove the comment outside the template, or teach this script to tokenise.`
    );
  }
}

function strip(src) {
  const out = [];
  let inBlock = false;
  for (const ln of src.split("\n")) {
    const t = ln.trim();
    if (inBlock) { if (t.endsWith("*/")) inBlock = false; continue; }
    if (t === "") continue;
    if (t.startsWith("//")) continue;
    if (t.startsWith("/*")) {
      if (t.endsWith("*/")) continue;                 // a one-line block comment
      if (!t.includes("*/")) { inBlock = true; continue; }
      out.push(ln); continue;                          // code after a closing */: leave alone
    }
    out.push(ln);
  }
  return out.join("\n") + "\n";
}

const BANNER = (name) =>
  `/*! Garbage Rips 585 - generated by scripts/build-js.mjs.\n` +
  `    EDIT assets-source/js/${name}, NOT THIS FILE. Identical code with the\n` +
  `    comments stripped; the commented original is the source. */\n`;

if (import.meta.url === `file://${process.argv[1]}`) {
  let wrote = 0, saved = 0;
  for (const name of (await readdir(SRC)).filter((f) => f.endsWith(".js")).sort()) {
    const src = await readFile(join(SRC, name), "utf8");
    assertNoTemplateComments(name, src);
    const out = BANNER(name) + strip(src);
    await writeFile(join(OUT, name), out);
    wrote += 1;
    saved += src.length - out.length;
    console.log(`  ${name.padEnd(16)} ${(src.length / 1024).toFixed(1)} -> ${(out.length / 1024).toFixed(1)} KB`);
  }
  console.log(`${wrote} script(s), ${(saved / 1024).toFixed(1)} KB of comments left in assets-source/js/`);
}
