#!/usr/bin/env python3
"""Turn pack artwork masters into web-sized files plus the CSS that uses them.

    python3 scripts/build-packs.py

Drop masters in assets-source/packs/ named by set id (pitch-black.png,
chaos-rising.png, default.png ...). This writes optimised WebP to
public/assets/packs/ and generates public/assets/packs.css, which is what
actually swaps a set's gradient for its artwork. A set with no master keeps
its colour design, so this is safe to run with one file or twenty.

Needs Pillow: python3 -m pip install --user Pillow
"""
import os
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets-source" / "packs"
OUT = ROOT / "public" / "assets" / "packs"
CSS = ROOT / "public" / "assets" / "packs.css"

# 810x1440 covers both places the pack renders: the rip page player needs
# 760px across at 2x, tiles need 534. One file, no srcset gymnastics.
TARGET = (810, 1440)
# A tile is never wider than about 200 CSS px, so 400 covers it at 2x. The full
# size exists for one place only: the rip page player, which is ~380 CSS px and
# needs 760. Serving 810x1440 into a 197px tile was a 4x linear oversample and
# put 1.6 MB of pack art on the home page.
TILE = (400, 711)
# THE MIDDLE RENDITION, ADDED 16 AUGUST 2026, AND IT EXISTS FOR ONE MEASUREMENT.
# With only 400 and 810 to choose from, EVERY pack request on the home page took
# the 810 file at every width and every DPR: logged from the network with cache
# off, 5 packs at 1280, 1440 and 1920, none of them ever landing on the tile.
#
# The home page's carousel art measures 328px at 1280, 373 to 378 at 1440 and
# 391 to 408 at 1920, and the Hall of Fame frame 404 to 464. On a DPR 1 desktop
# every one of those boxes is over 400 and under 560, so 400w cannot satisfy it
# and 810w is the only thing left. 560 is the width that sits in that gap, and
# it wins at all three desktop widths WITHOUT anybody writing ui.css's
# 1000/1200/1400 slide-count breakpoints a second time into a `sizes` attribute
# in build-proto.mjs. See the "NO MEDIA QUERY IN HERE" note in heroTile.
#
# IT IS A DPR 1 FIX AND ONLY A DPR 1 FIX, which is the honest way to sell it. At
# DPR 2 a 402px box needs 804 device pixels and 810w is already the smallest
# candidate that satisfies it, so a retina laptop and every modern phone fetch
# exactly what they fetched before, byte for byte. That is also why it is safe:
# it cannot make the phone worse. Measured: 681.6KB of pack art on the home page
# becomes 375.5KB at DPR 1, and stays 681.6KB at DPR 2 and DPR 3.
#
# 700w WAS DELIBERATELY NOT ADDED. It was measured with the files generated and
# was picked in exactly one case, a DPR 2 phone, for 19 more files and 2MB.
MID = (560, 996)
QUALITY = 78
BACKDROP = "#161D26"  # shows through the transparent margin around the pack

SRC.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)

masters = sorted(
    p for p in SRC.iterdir()
    if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp") and not p.name.startswith(".")
)

if not masters:
    print(f"No masters found in {SRC.relative_to(ROOT)}/")
    print("Drop 1080x1920 artwork named by set id, e.g. pitch-black.png")
    raise SystemExit(0)

rules = [
    "/* Generated by scripts/build-packs.py. Do not edit by hand. */",
    "/* A set listed here shows its artwork; every other set keeps the",
    "   colour design in site.css. */",
    "",
]
done = []
for m in masters:
    set_id = m.stem
    im = Image.open(m)
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    full = im.copy()
    full.thumbnail(TARGET, Image.LANCZOS)
    dest = OUT / f"{set_id}-garbage-rips-585-booster-pack.webp"
    full.save(dest, "WEBP", quality=QUALITY, method=6)

    tile = im.copy()
    tile.thumbnail(TILE, Image.LANCZOS)
    tile_dest = OUT / f"{set_id}-garbage-rips-585-booster-pack-tile.webp"
    tile.save(tile_dest, "WEBP", quality=QUALITY, method=6)

    mid = im.copy()
    mid.thumbnail(MID, Image.LANCZOS)
    mid_dest = OUT / f"{set_id}-garbage-rips-585-booster-pack-mid.webp"
    mid.save(mid_dest, "WEBP", quality=QUALITY, method=6)

    kb = dest.stat().st_size / 1024
    tkb = tile_dest.stat().st_size / 1024
    mkb = mid_dest.stat().st_size / 1024
    done.append((set_id, full.size, kb, m.stat().st_size / 1024, tile.size, tkb, mid.size, mkb))

    sel = f".pack--{set_id}"
    rules += [
        f"{sel} .pack-art{{",
        f"  background-color:{BACKDROP};",
        f"  background-image:url('packs/{set_id}-garbage-rips-585-booster-pack.webp');",
        "  background-size:cover;",
        "  background-position:center;",
        "}",
        # The artwork carries its own wordmark and mascot, so the generated
        # ones would sit on top of it.
        f"{sel} .pack-art::before,{sel} .pack-art::after{{content:none}}",
        f"{sel} .pack-brand,{sel} .pack-mascot{{display:none}}",
        # A tile is never wider than about 200 CSS px. Pointing it at the 810px
        # file was a 4x oversample, and the library draws 48 of them at once.
        f"{sel}.pack--tile .pack-art{{",
        f"  background-image:url('packs/{set_id}-garbage-rips-585-booster-pack-tile.webp');",
        "}",
        "",
    ]

# The Hall of Fame recolours every pack gold, which artwork would override.
#
# SCOPED TO THE HALL PAGE'S OWN CONTAINER, NOT TO ".hall".
# This was written as `.hall .pack ...` when the Hall of Fame page's wrapper was
# called .hall. build-hall.mjs now emits .chofpage, so the only markup left
# carrying a `hall` class is <main class="rip tight hall"> on the two rip pages
# whose video is flagged `greatest` in build-pages.mjs. That meant these three
# rules hit nothing they were written for and exactly two things they were not:
# at (0,3,0) they outrank `.pack--<set> .pack-art` at (0,2,0), so both of those
# rip pages threw away the commissioned pack photo, fell back to the generic
# gradient, and switched the "GARBAGE RIPS 585" text overlay back on. Silent,
# because a losing background-image is not an error, and invisible from the
# generator, which cannot see what class the page builders emit.
#
# Keep the selector pointing at the Hall of Fame page itself. hall.html renders
# no packs today, so these are inert; they cost nothing and they are the guard
# that has to exist the moment it does render one.
rules += [
    "/* Hall of Fame stays gold even for sets that have artwork. The gold is",
    "   painted with gradients, so simply clearing background-image blanked",
    "   these to a flat dark rectangle. Restore the gradients explicitly.",
    "   Scoped to .chofpage, the Hall of Fame page's own wrapper. It used to say",
    "   .hall, which no longer matches that page and DID match the two rip pages",
    "   for a `greatest` video, blanking their pack artwork. */",
    ".chofpage .pack .pack-art{",
    "  background-color:transparent;",
    "  background-image:",
    "    radial-gradient(120% 70% at 50% 12%,rgba(255,255,255,.22),transparent 60%),",
    "    linear-gradient(160deg,var(--pk-a) 0%,var(--pk-b) 38%,var(--pk-c) 72%,var(--pk-d) 100%);",
    "}",
    ".chofpage .pack .pack-art::before{content:\"\"}",
    ".chofpage .pack .pack-brand{display:block}",
    "",
]

CSS.write_text("\n".join(rules))

print(f"Wrote {len(done)} pack set(s), three renditions each, to {OUT.relative_to(ROOT)}/")
for set_id, size, kb, src_kb, tsize, tkb, msize, mkb in done:
    print(f"  {set_id:<24} {size[0]:>4}w {kb:6.1f} KB   "
          f"{msize[0]:>4}w {mkb:6.1f} KB   {tsize[0]:>4}w {tkb:6.1f} KB   (from {src_kb:.0f} KB)")
print(f"\nWrote {CSS.relative_to(ROOT)}")

# ---------------------------------------------------------------- packshots
# Photos of the REAL retail booster packs, for the set pages. These have to be
# pictures you took yourself of packs you own: official product photography is
# not ours to copy. Any set without one just hides that panel.
SHOT_SRC = ROOT / "assets-source" / "packshots"
SHOT_OUT = ROOT / "public" / "assets" / "packshots"
SHOT_SRC.mkdir(parents=True, exist_ok=True)
SHOT_OUT.mkdir(parents=True, exist_ok=True)

shots = sorted(
    p for p in SHOT_SRC.iterdir()
    if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp") and not p.name.startswith(".")
)
if shots:
    print()
    for m in shots:
        im = Image.open(m)
        if im.mode not in ("RGB", "RGBA"):
            im = im.convert("RGBA")
        im.thumbnail((720, 1080), Image.LANCZOS)
        dest = SHOT_OUT / f"{m.stem}-booster-pack.webp"
        im.save(dest, "WEBP", quality=80, method=6)
        print(f"  packshot {m.stem:<22} {im.size[0]}x{im.size[1]}  {dest.stat().st_size/1024:6.1f} KB")
    print(f"\nWrote {len(shots)} packshot(s) to {SHOT_OUT.relative_to(ROOT)}/")
else:
    print(f"\nNo packshots in {SHOT_SRC.relative_to(ROOT)}/ yet.")
    print("Drop photos of real booster packs named by set id (pitch-black.jpg).")
